# ======================================================
# Node: temp
# - Reuses base + wifi packages
# - Enables BLE tracker (passive) for ATC thermometers
# - Includes the reusable BLE ATC pack for each sensor
# ======================================================

substitutions:
  name: temp   # Used by base.yaml (esphome.name, friendly_name, etc.)

# BLE tracker: passive scan saves power/CPU/RAM vs active
esp32_ble_tracker:
  scan_parameters:
    active: false          # Passive scanning; good for ATC beacons
    interval: 320ms        # Keep as configured; higher interval = less CPU
    window: 30ms           # Must be <= interval; increases chance to catch beacons

# Narrow noisy component logs without changing global level from base.yaml
logger:
  logs:
    atc_mithermometer: WARN  # Reduce BLE parser spam in logs
prometheus:
packages:
  base:  !include packages/base.yaml
  wifi:  !include packages/wifi.yaml

  # Each pack instance provides:
  # - <room> temp / hum / batt sensors
  # - <room> update (ISO-8601 timestamp text_sensor)
  ble_kitchen: !include
    file: packages/ble_atc_pack.yaml
    vars: { room: kitchen, mac: "A4:C1:38:38:E9:1B" }

  ble_plant: !include
    file: packages/ble_atc_pack.yaml
    vars: { room: plant,   mac: "A4:C1:38:0E:1C:EE" }

  ble_street: !include
    file: packages/ble_atc_pack.yaml
    vars: { room: street,  mac: "A4:C1:38:45:36:6F" }