# file : temp.yaml

substitutions:
  name: temp


esphome:
  name: ${name}

esp32:
  board: esp32dev

esp32_ble_tracker:
    scan_parameters:
      active: false
      interval: 320ms
      window: 30ms

logger:
  logs:
    atc_mithermometer: WARN

packages:
  base:  !include packages/base.yaml
  wifi:  !include packages/wifi.yaml
  # твои BLE-подключения...
  ble_kitchen: !include
    file: packages/ble_atc_pack.yaml
    vars: { room: kitchen, mac: "A4:C1:38:38:E9:1B" }
  ble_plant: !include
    file: packages/ble_atc_pack.yaml
    vars: { room: plant,   mac: "A4:C1:38:0E:1C:EE" }
  ble_street: !include
    file: packages/ble_atc_pack.yaml
    vars: { room: street,  mac: "A4:C1:38:45:36:6F" }

  # display: !include packages/display_epaper.yaml

